name: neuconw
channels:
  - pytorch-lts
  - nvidia
  - defaults
  # - conda-forge
dependencies:
  - python=3.8
  - pytorch 
  - torchvision 
  - torchaudio 
  - cudatoolkit=11.1
  - ipython
  - tqdm
  - pip
  - pip:
    - -r requirements.txt
    - git+https://github.com/Burningdust21/kaolin.git
